// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_controller_active from "./routes/api/controller/active.ts";
import * as $api_signal from "./routes/api/signal.ts";
import * as $api_signal_clients from "./routes/api/signal/clients.ts";
import * as $api_signal_send from "./routes/api/signal/send.ts";
import * as $api_twilio_ice from "./routes/api/twilio-ice.ts";
import * as $ctrl_callback from "./routes/ctrl/callback.tsx";
import * as $ctrl_dev from "./routes/ctrl/dev.tsx";
import * as $ctrl_index from "./routes/ctrl/index.tsx";
import * as $ctrl_logout from "./routes/ctrl/logout.tsx";
import * as $index from "./routes/index.tsx";
import * as $Controller from "./islands/Controller.tsx";
import * as $KickControllerButton from "./islands/KickControllerButton.tsx";
import * as $Synth from "./islands/Synth.tsx";
import * as $WebRTC from "./islands/WebRTC.tsx";
import * as $hooks_clientManagerStore from "./islands/hooks/clientManagerStore.ts";
import * as $hooks_useAudioEngine from "./islands/hooks/useAudioEngine.ts";
import * as $hooks_useClientManager from "./islands/hooks/useClientManager.ts";
import * as $hooks_useWebSocketSignaling from "./islands/hooks/useWebSocketSignaling.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/controller/active.ts": $api_controller_active,
    "./routes/api/signal.ts": $api_signal,
    "./routes/api/signal/clients.ts": $api_signal_clients,
    "./routes/api/signal/send.ts": $api_signal_send,
    "./routes/api/twilio-ice.ts": $api_twilio_ice,
    "./routes/ctrl/callback.tsx": $ctrl_callback,
    "./routes/ctrl/dev.tsx": $ctrl_dev,
    "./routes/ctrl/index.tsx": $ctrl_index,
    "./routes/ctrl/logout.tsx": $ctrl_logout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Controller.tsx": $Controller,
    "./islands/KickControllerButton.tsx": $KickControllerButton,
    "./islands/Synth.tsx": $Synth,
    "./islands/WebRTC.tsx": $WebRTC,
    "./islands/hooks/clientManagerStore.ts": $hooks_clientManagerStore,
    "./islands/hooks/useAudioEngine.ts": $hooks_useAudioEngine,
    "./islands/hooks/useClientManager.ts": $hooks_useClientManager,
    "./islands/hooks/useWebSocketSignaling.ts": $hooks_useWebSocketSignaling,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
